import {
  backendGetWordPackResponseSchema,
  wordPackResponseSchema,
  type WordPackResponse,
} from "@/features/rooms/word-pack";
import { roomCodeInputSchema } from "@/features/rooms/room-code";
import { requestBackend } from "@/lib/api/backend";
import {
  frontendApiErrorResponse,
  normalizeBackendError,
  normalizeValidationError,
  type FrontendApiError,
} from "@/lib/api/errors";
import { hasTrustedMutationOrigin } from "@/lib/api/mutation-request";
import { getSessionToken } from "@/lib/auth/session-cookie";
import { serverEnv } from "@/lib/env/server";

const DEFAULT_ROOM_WORDS = [
  "castle",
  "dragon",
  "wizard",
  "sword",
  "potion",
  "goblin",
  "treasure",
  "shield",
];

const backendUnavailableError: FrontendApiError = {
  status: 502,
  code: "server_error",
  message: "The word pack service is temporarily unavailable.",
};

type RouteContext = {
  params: Promise<{
    roomCode: string;
  }>;
};

export async function POST(
  request: Request,
  context: RouteContext,
): Promise<Response> {
  if (!hasTrustedMutationOrigin(request, serverEnv.APP_ORIGIN)) {
    return frontendApiErrorResponse({
      status: 403,
      code: "forbidden",
      message: "The request origin is not allowed.",
    });
  }

  const { roomCode: rawRoomCode } = await context.params;
  const parsedRoomCode = roomCodeInputSchema.safeParse(rawRoomCode);
  if (!parsedRoomCode.success) {
    return frontendApiErrorResponse(
      normalizeValidationError(parsedRoomCode.error),
    );
  }

  const token = await getSessionToken();
  if (!token) {
    return frontendApiErrorResponse({
      status: 401,
      code: "unauthorized",
      message: "Authentication is required.",
    });
  }

  let createdWordPackId: string;

  try {
    const createPackResponse = await requestBackend("/v1/word-packs", {
      bearerToken: token,
      json: createTemporaryWordPackInput(parsedRoomCode.data),
      method: "POST",
    });

    if (!createPackResponse.ok) {
      return frontendApiErrorResponse(
        await normalizeBackendError(createPackResponse),
      );
    }

    const parsedCreatePackResponse = wordPackResponseSchema.safeParse(
      await createPackResponse.json().catch(() => undefined),
    );
    if (!parsedCreatePackResponse.success) {
      return frontendApiErrorResponse(backendUnavailableError);
    }

    createdWordPackId = parsedCreatePackResponse.data.word_pack.id;

    for (const word of DEFAULT_ROOM_WORDS) {
      const createWordResponse = await requestBackend(
        `/v1/word-packs/${encodeURIComponent(createdWordPackId)}/words`,
        {
          bearerToken: token,
          json: {
            difficulty: "medium",
            text: word,
          },
          method: "POST",
        },
      );

      if (!createWordResponse.ok) {
        return frontendApiErrorResponse(
          await normalizeBackendError(createWordResponse),
        );
      }
    }

    const getPackResponse = await requestBackend(
      `/v1/word-packs/${encodeURIComponent(createdWordPackId)}`,
      {
        bearerToken: token,
        method: "GET",
      },
    );

    if (!getPackResponse.ok) {
      return frontendApiErrorResponse(
        await normalizeBackendError(getPackResponse),
      );
    }

    const parsedGetPackResponse = backendGetWordPackResponseSchema.safeParse(
      await getPackResponse.json().catch(() => undefined),
    );
    if (!parsedGetPackResponse.success) {
      return frontendApiErrorResponse(backendUnavailableError);
    }

    const responseBody: WordPackResponse = {
      word_pack: parsedGetPackResponse.data.word_pack,
    };

    return Response.json(responseBody, {
      status: 201,
      headers: {
        "Cache-Control": "no-store",
      },
    });
  } catch {
    return frontendApiErrorResponse(backendUnavailableError);
  }
}

function createTemporaryWordPackInput(roomCode: string) {
  const uniqueSuffix = crypto.randomUUID().slice(0, 8);

  return {
    description:
      "Temporary room word pack generated by the frontend lobby flow.",
    is_active: true,
    name: `Room ${roomCode} Starter Pack`,
    slug: `room-${roomCode.toLowerCase()}-${uniqueSuffix}`,
  };
}
